
Post http://localhost:3000/api/vzconn/auth/register
Content-Type: application/json

{
    "username": "truongtran04",
    "password": "Truong@123",
    "email": "trantruong@gmail.com",
    "name": "Trần Nguyên Trường",
    "phonenumber": "0359375875"
}

###

GET http://localhost:3000/api/vzconn/product