###TÀI KHOẢN###
Post http://localhost:3000/api/v1/vzconn/auth/register
Content-Type: application/json

{
    "username": "truongtran05",
    "password": "Truong@123",
    "email": "trantruong@gmail.com",
    "fullname": "Trần Nguyên Trường",
    "phonenumber": "0359375875"
}

###
###LOGIN TK KHÁCH###
###
Post http://localhost:3000/api/v1/vzconn/auth/login
Content-Type: application/json

{
    "username": "truongtran05",
    "password": "Truong@123"
    
}

###LOGIN TK NHÂN VIÊN###
###
Post http://localhost:3000/api/v1/vzconn/auth/login
Content-Type: application/json

{
    "username": "truongtran02",
    "password": "Truong@123"
    
}

###LOGOUT
Post http://localhost:3000/api/v1/vzconn/auth/logout

########################################################
###
POST http://localhost:3000/api/v1/vzconn/auth/forgotPassword
Content-Type: application/json

{
    "email": "trantruong@gmail.com"
}

###
POST http://localhost:3000/api/v1/vzconn/auth/ResetPassword/d620a93f098cc0d6076de4b38868082c10abe26fa51d8f7f869a40549e5c
Content-Type: application/json

{
    "password": "Truong@321"
}

###
POST http://localhost:3000/api/v1/vzconn/auth/ChangePassword
Content-Type: application/json

{
    "password": "Truong@123"
}

###
###THÔNG TIN NGƯỜI DÙNG###
###
GET http://localhost:3000/api/v1/vzconn/user/profile

###
GET http://localhost:3000/api/v1/vzconn/employee/profile

###
###THÔNG TIN NHÂN VIÊN###
###

######### MUA HÀNG #######
###
POST http://localhost:3000/api/v1/vzconn/order/createNew

###
POST http://localhost:3000/api/v1/vzconn/order/intobill
Content-Type: application/json

{
    "IdProduct": "7-4-2024 15:36:5EhPsL"
}

###
###SẢN PHẨM####
###
POST http://localhost:3000/api/v1/vzconn/product
Content-Type: application/json

{
    "name": "Bàn phím Sugar 65",
    "image": "https://bizweb.dktcdn.net/100/438/322/products/z4589506891972-a2e366ca3e7b4783834c62aad399ebec-17b66ee9-cab6-44a3-83fb-dc22f23ceca6.jpg?v=1696392929720",
    "title": "Bàn phím tương tự nhưng tăng giá hơn",
    "SLT":10,
    "price": 1100000,
    "typeid": "BPC"
}

###

POST http://localhost:3000/api/v1/vzconn/product
Content-Type: application/json

{
    "name": "Bàn phím XinMeng A66",
    "image": "https://bizweb.dktcdn.net/thumb/1024x1024/100/436/596/products/5-1692543376602.png?v=1692543382313",
    "title": "Bàn phím trung quốc",
    "SLT":10,
    "price": 1100000,
    "typeid": "BPC"
}
###

DELETE http://localhost:3000/api/v1/vzconn/product/66125af5e01286fc10f21ee5


###
GET http://localhost:3000/api/v1/vzconn/user/6619f196c4132eaa9cdd97b1

### THÊM LOẠI SẢN PHẨM ###
POST http://localhost:3000/api/v1/vzconn/type
Content-Type: application/json

{
    "id": "CMT",
    "name": "Chuột máy tính"
}

### 
POST http://localhost:3000/api/v1/vzconn/type
Content-Type: application/json

{
    "id": "BPC",
    "name": "Bàn phím cơ"
}

## Loại Sản phẩm
GET http://localhost:3000/api/v1/vzconn/type

###
GET http://localhost:3000/api/v1/vzconn/product/admin/getproduct

###
GET http://localhost:3000/api/v1/vzconn/user/admin/getuser